import pandas as pd

def make_diary():
    diary_lst = ["오늘은 맑은 하늘이라 기분이 좋다.",
                '아침에 일어나서 창문을 열어보니 새소리가 들려서 기분이 좋았다.',
                '학교에 가는 길에 꽃 향기가 나서 기분이 좋아졌다.',
                '수업 시간에 친구랑 재미있는 이야기를 나눴다.',
                '점심 시간에 맛있는 음식을 먹어서 배가 부르다.',
                '집에 돌아와서 가족들과 함께 저녁을 먹었다.',
                '밤에는 별이 아주 많이 보여서 감탄했다.',
                '오늘은 피곤하지만 행복한 하루였다.',
                '오늘은 비가 와서 실내에서 영화를 보면서 보냈다.',
                '하루 종일 친구들과 함께 놀았더니 정말 행복했다.',
                '오늘은 나의 생일이라서 친구들이 축하해주었다.',
                '아침에 일어나자마자 새벽 풍경을 구경하러 나갔다.',
                '오랜만에 가족들과 함께 여행을 다녀왔다.',
                '가을이라서 나뭇잎이 노란색으로 변하는 모습이 아름답다.',
                '오늘은 카페에서 책을 읽으면서 커피를 마셨다.',
                '밤에는 달이 아름답게 떠서 창밖을 바라보았다.',
                '오늘은 나의 꿈을 이루기 위해 열심히 노력한 날이었다.',
                '오랜만에 친구들과 만나서 함께 놀아서 기분이 좋다.',
                '오늘은 사랑하는 사람과 함께 보내는 특별한 날이다.',
                '아침에 일어나서 창문을 열어보니 산머루 꽃이 피어있어서 기분이 좋았다.',
                '점심에는 새로운 음식을 시도했는데 맛있어서 놀랐다.',
                '오후에는 공원에서 산책을 하면서 시간을 보냈다.',
                '저녁에는 가족들과 함께 맛있는 음식을 먹으면서 이야기를 나눴다.',
                '밤에는 별을 보면서 소망을 했다.',
                '오늘은 감정이 복잡하지만 잘 해결했다.',
                '새로운 취미를 발견해서 즐겁다.',
                '오랜만에 가족들과 함께 모여서 저녁을 먹었다.',
                '오늘은 좋은 소식을 듣고 기뻤다.',
                '가을 햇살이 아름다워서 더욱 기분이 좋다.',
                '아침에 일찍 일어나서 해돋이를 보러 나갔다.',
                '점심에는 새로운 레스토랑을 가서 맛있는 음식을 먹었다.',
                '오후에는 카페에서 공부를 하면서 시간을 보냈다.',
                '저녁에는 친구들과 함께 맛있는 저녁을 먹으면서 이야기를 나눴다.',
                '밤에는 조용한 산책을 하면서 마음을 가다듬었다.',
                '오늘은 꿈에서 만난 사람을 생각하며 하루를 시작했다.',
                '새로운 일에 도전해서 성공해서 기뻤다.',
                '오랜만에 가족들과 함께 영화를 보고 재미있게 놀았다.',
                '오늘은 친구의 생일이라서 축하파티를 준비했다.',
                '아침에 일찍 일어나서 해변을 거닐었다.',
                '오후에는 공원에서 책을 읽으면서 쉬었다.',
                '저녁에는 가족들과 함께 맛있는 저녁을 먹었다.',
                '밤에는 친구들과 함께 캠프파이어를 지키면서 이야기를 나눴다.',
                '오늘은 마음이 가라앉아서 조용한 하루였다.',
                '가을 햇살이 따뜻해서 밖에서 시간을 보내기 좋았다.',
                '오늘은 좋은 기운을 받아서 행복한 하루였다.',
                '친구들과 함께 축구를 하면서 즐거웠다.',
                '오늘은 바다를 보면서 여유로운 시간을 보냈다.',
                "오늘은 흐린 날씨라 기분이 우울했어.",
                "일어나자마자 기분이 좋지 않았어.",
                "길을 걷는데 꽃이 시들어 있어서 마음이 우울했어.",
                "수업 시간에 친구랑 대화를 나누는 것도 재미없었어.",
                "점심에 먹은 음식도 맛이 없어서 실망했어.",
                "도서관에 가서 책을 읽으려 했지만 집중이 안 되어서 힘들었어.",
                "가족들과 저녁을 먹으면서도 마음이 무겁고 우울했어.",
                "밤하늘이 어둡고 우울했어.",
                "오늘은 힘든 하루였어.",
                "비가 오는 날씨에 집에만 있어서 우울했어.",
                "친구들과 함께 있어도 마음이 편하지 않았어.",
                "내 생일이지만 기대하던 것보다 기분이 나쁘고 우울했어.",
                "해돋이를 보러 나갔지만 기분이 좋지 않았어.",
                "가족과 여행을 다녀와도 마음이 우울했어.",
                "가을이라 나뭇잎이 떨어지는 모습이 서글했어.",
                "카페에 가서 커피를 마셨지만 기분이 나아지지 않았어.",
                "별이 보이지 않아서 마음이 우울했어.",
                "오늘은 실패한 것 같아서 우울했어.",
                "친구들과 만나도 마음이 가라앉지 않았어.",
                "사랑하는 사람과 함께해도 마음이 무거웠어.",
                "새로운 요리를 만들어봤지만 맛이 없어서 실망했어.",
                "산책하러 나갔지만 마음이 가라앉지 않아서 힘들었어.",
                "가족과 함께 있어도 마음이 무거웠어.",
                "밤하늘이 흐려서 별이 보이지 않아서 마음이 우울했어.",
                "오늘은 마음이 복잡해서 우울했어.",
                "새로운 취미를 발견해도 기분이 나아지지 않았어.",
                "가족과 함께 있어도 마음이 무겁고 우울했어.",
                "좋은 소식을 들어도 마음이 가라앉지 않았어."]

    prompt_lst=['Create a cute and funny 8k webtoon style illustration where a clear sunny sky that reflects the happy mood of the day as described in the diary entry.', 
                'Create a cute and funny 8k webtoon style illustration where a person waking up in the morning, opening the window, and feeling happy upon hearing the sound of birds chirping outside.', 
                'Create a cute and funny 8k webtoon style illustration where a person is walking to school and feeling happy because they smelled the scent of flowers along the way.', 
                'Create a cute and funny 8k webtoon style illustration where you and your friend are having an interesting conversation during class.', 
                'Create a cute and funny 8k webtoon style illustration where a character eats delicious food during lunchtime and their belly gets so full that it looks like a balloon about to pop.', 
                'Create a cute and funny 8k webtoon style illustration where the user returns home and has dinner with their family, capturing the joy of family bonding over a meal.', 
                'Create a cute and funny 8k webtoon style illustration where a person gazing up at the night sky, marveling at the abundance of stars twinkling above, capturing the sense of wonder and awe experienced by the observer.',
                'Create a cute and funny 8k webtoon style illustration where a person has a tired but happy day, capturing the essence of the day described in the diary entry.', 
                "Create a cute and funny 8k webtoon style illustration of a cozy indoor scene where it's raining outside. Show a person watching a movie in a warm and comfortable setting with soft lighting and a mug of hot drink.", 
                'Create a cute and funny 8k webtoon style illustration where a day spent playing with friends and feeling truly happy. ', 
                'Create a cute and funny 8k webtoon style illustration of a birthday celebration where friends are cheerfully congratulating the protagonist.', 
                'Create a cute and funny 8k webtoon style illustration where the character wakes up in the morning and goes outside to enjoy the early morning scenery. The scene should be filled with charming details of the break of dawn and the beauty of nature.', 
                'Create a cute and funny 8k webtoon style illustration where a family travel scene that I recently wrote about in my diary. The illustration should capture the joyful and heartwarming moments of my family trip.', 
                'Create a cute and funny 8k webtoon style illustration where the beauty of autumn with yellow leaves changing color.', 
                'Create a cute and funny 8k webtoon style illustration where a character read a book and drinking coffee in a cafe.', 
                'Create a cute and funny 8k webtoon style illustration about a lovely scene of the beautiful moon rising outside your window and shining brightly in the night sky.', 
                'Create a cute and funny 8k webtoon style illustration where the protagonist works hard to achieve their dream.', 
                'Create a cute and funny 8k webtoon style illustration about a scene of me meeting my friends after a long time and having a great time together.', 
                'Create a cute and funny 8k webtoon style illustration about a special day spent with a loved one.', 
                'Create a cute and funny 8k webtoon style illustration of a character waking up in the morning, opening a window, and feeling happy seeing cherry blossoms blooming outside.', 
                'Create a cute and funny 8k webtoon style illustration of a person trying a new, surprisingly tasty dish for lunch.', 
                'Create a cute and funny 8k webtoon style illustration of a person walking in the park in the afternoon."', 
                'Create a cute and funny 8k webtoon style illustration where a family is sitting around a dinner table, enjoying delicious food and having a lively conversation. ', 
                'Create a cute and funny 8k webtoon style illustration where I make a wish while looking at the stars at night.', 
                'Create a cute and funny 8k webtoon style illustration of a person with complex emotions, but successfully resolving them.', 
                'Create a cute and funny 8k webtoon style illustration of a person joyfully discovering a new hobby in a webtoon style.', 
                'Create a cute and funny 8k webtoon style illustration of a family gathering for dinner after a long time apart.', 
                'Create a cute and funny 8k webtoon style illustration of a joyful moment of hearing good news.',
                'Create a cute and funny 8k webtoon style illustration of a beautiful autumn sunlight brightening up the mood.', 
                'Create a cute and funny 8k webtoon style illustration of a person waking up early in the morning to watch the sunrise.', 
                'Create a cute and funny 8k webtoon style illustration of a character visiting a new restaurant for lunch and enjoying delicious food.', 
                'Create a cute and funny 8k webtoon style illustration where a person is studying while sipping coffee.', 
                'Create a cute and funny 8k webtoon style illustration of friends enjoying a delicious dinner together and sharing stories in the evening.', 
                'Create a cute and funny 8k webtoon style illustration of a person taking a peaceful evening walk in the mountains to clear their mind.', 
                'Create a cute and funny 8k webtoon style illustration featuring the person you met in your dream, as you start your day thinking about them.', 
                'Create a cute and funny 8k webtoon style illustration of a character successfully taking on a new challenge', 
                "Create a cute and funny 8k webtoon style illustration of a family outing where they are watching a movie together.", 
                'Create a cute and funny 8k webtoon style illustration of a birthday party preparation for a friend.', 
                'Create a cute and funny 8k webtoon style illustration depicting a person waking up early and strolling along the beach in the morning.', 
                "Create a cute and funny 8k webtoon style illustration where a character is reading a book in a park.", 
                'Create a cute and funny 8k webtoon style illustration where a family is enjoying a delicious dinner together.', 
                'Create a cute and funny 8k webtoon style illustration of friends sitting around a campfire sharing stories in the night.', 
                'Create a cute and funny 8k webtoon style illustration that depicts a calm and soothing day where the heart is at peace.', 
                'Create a cute and funny 8k webtoon style illustration depicting a warm autumn sun shining outside, making it perfect to spend time outdoors, with a cute and cozy atmosphere.', 
                'Create a cute and funny 8k webtoon style illustration that depicts a day filled with positive energy and happiness.', 
                'Create a cute and funny 8k webtoon style illustration of friends playing soccer and having fun together.', 
                'Create a cute and funny 8k webtoon style illustration of a person enjoying a leisurely time while looking at the sea.',
                "Create a cute and funny 8k webtoon style illustration depicting a cloudy day that matches the writer's melancholic mood.", 
                'Create a cute and funny 8k webtoon style illustration of a character waking up in a grumpy mood.', 
                'Create a cute and funny 8k webtoon style illustration of a person walking down a path with wilted flowers, looking sad.', 
                'Create a cute and funny 8k webtoon style illustration where a student is talking to a friend during class and finding it not enjoyable.', 
                'Create a cute and funny 8k webtoon style illustration of a disappointed person looking at unappetizing food during lunchtime.', 
                'Create a cute and funny 8k webtoon style illustration depicting a person struggling to concentrate while trying to read a book at the library.', 
                'Create a cute and funny 8k webtoon style illustration of a family having dinner together, but with a heavy and melancholic atmosphere.', 
                'Create a cute and funny 8k webtoon style illustration of a dark and gloomy night sky, with stars twinkling brightly to bring a sense of hope and comfort.', 
                'Create a cute and funny 8k webtoon style illustration that depicts a person having a tough day.', 
                'Create a cute and funny 8k webtoon style illustration that depicts a cute scene of someone feeling gloomy while staying at home on a rainy day.', 
                'Create a cute and funny 8k webtoon style illustration where the diary writer is with friends but still feels uneasy, ', 
                'Create a cute and funny 8k webtoon style illustration depicting a character celebrating their birthday feeling disappointed and sad instead of happy and excited.', 
                'Create a cute and funny 8k webtoon style illustration where a character is going to watch the sunrise, but feeling downcast.', 
                'Create a cute and funny 8k webtoon style illustration in which a family goes on a trip together, but the main character still feels melancholic despite the happy occasion.', 
                'Create a cute and funny 8k webtoon style illustration depicting the sadness of falling leaves in autumn.', 
                'Create a cute and funny 8k webtoon style illustration of a person sitting in a cafe, looking disappointed while drinking coffee.', 
                "Create a cute and funny 8k webtoon style illustration of a character feeling melancholic because they couldn't see any stars in the sky.", 
                "Create a cute and funny 8k webtoon style illustration of a character feeling down and dejected after what seems like a failed day.", 
                'Create a cute and funny 8k webtoon style illustration depicting a group of friends meeting up, where despite the cheerful atmosphere, one friend looks thoughtful and pensive, struggling to find inner peace.', 
                'Create a cute and funny 8k webtoon style illustration depicting a person feeling heavy-hearted even when being with their loved one.', 
                'Create a cute and funny 8k webtoon style illustration of someone looking disappointed after trying a new recipe and finding it not tasty.', 
                'Create a cute and funny 8k webtoon style illustration of a character going out for a walk, but their heart is visibly heavy and the surroundings reflect their inner turmoil.', 
                'Create a cute and funny 8k webtoon style illustration depicting a person surrounded by their family, but with a heavy heart.', 
                'Create a cute and funny 8k webtoon style illustration of a cloudy night sky making the stars invisible, leading to a feeling of sadness.', 
                'Create a cute and funny 8k webtoon style illustration that depicts a person feeling sad and confused. The character should be sitting alone with a pensive expression, surrounded by colorful thought bubbles showing various conflicting emotions.', 
                'Create a cute and funny 8k webtoon style illustration of a person discovering a new hobby but still feeling down despite it.', 
                'Create a cute and funny 8k webtoon style illustration depicting a scene where a person is with their family but feeling heavy-hearted and melancholic.', 
                "Create a cute and funny 8k webtoon style illustration where the protagonist is hearing good news but their heart doesn't lift up."]

# "누구랑: 가족/무엇을: 오늘은 가족들과 함께 우리 집 근처 공원에서 피크닉을 즐겼어. 엄마가 준비해 온 간식과 함께 나무 그늘 아래에서 책을 읽으며 시간을 보냈어./어디에서: 공원",
# "누구랑: 친구/무엇을: 오늘은 친구와 함께 영화를 보러 갔어. 신나는 액션 영화를 시간 가는 줄 모르고 즐겼어. 마지막에는 함께 맛있는 음식을 먹으며 하루를 마무리했어./어디에서: 영화관",
# "누구랑: 혼자/무엇을: 오늘은 혼자 집에서 영화를 보며 휴식을 취했어. 책상에 앉아 컴퓨터 앞에서 쿠션에 누워 마음을 가라앉혔어./어디에서: 집",
# "누구랑: 반려동물/무엇을: 오늘은 강아지와 함께 공원을 산책했어. 바람을 맞으며 햇살 아래 걷는 것이 기분 좋았어. 강아지가 주는 사랑스러운 모습에 마음이 따뜻해졌어./어디에서: 공원",
# "누구랑: 동료/무엇을: 오늘은 동료들과 함께 회의를 진행했어. 아이디어를 공유하고 토론하는 과정에서 새로운 시각을 얻었고, 협업하는 느낌이 좋았어./어디에서: 회사",
# "누구랑: 남자친구/무엇을: 오늘은 산으로 등산을 다녀왔어. 힘들었지만 정상에서 보는 경치와 바람소리를 들으며 마음을 가다듬었어./어디에서: 산",
# "누구랑: 소중한 사람/무엇을: 오늘은 소중한 사람과 함께 기념일을 축하했어. 함께 맛있는 저녁을 먹으며 소중한 추억을 나눴어./어디에서: 레스토랑",
# "누구랑: 스스로/무엇을: 오늘은 스스로를 위한 시간을 가졌어. 집에서 조용한 음악을 들으며 마음을 정리하고 내 자신을 위한 다짐을 했어./어디에서: 집",
# "누구랑: 엄마/무엇을: 오늘은 엄마와 함께 요리를 했어. 엄마의 가르침을 받으며 함께 만든 음식을 먹는 것이 기쁘고 행복했어./어디에서: 부엌",
# "누구랑: 친구들/무엇을: 오늘은 친구들과 함께 카페에서 시간을 보냈어. 커피를 마시며 이야기를 나누고 함께하는 것이 즐거웠어./어디에서: 카페",
# "누구랑: 아이/무엇을: 오늘은 아이와 함께 공원에서 놀았어. 그의 순수한 미소와 함께 뛰어놀면서 잊지 못할 추억을 만들었어./어디에서: 공원",
# "누구랑: 사랑하는 이/무엇을: 오늘은 사랑하는 이와 함께 피크닉을 다녀왔어. 바람에 흔들리는 나뭇가지 소리와 함께하는 시간이 특별하고 행복했어./어디에서: 공원",
# "누구랑: 가족/무엇을: 오늘은 가족들과 함께 집에서 영화를 보았어. 함께 보는 것이 따뜻하고 편안했어./어디에서: 집",
# "누구랑: 친구/무엇을: 오늘은 친구와 함께 공원에서 자전거를 타고 놀았어. 바람을 맞으면서 즐거운 시간을 보냈어./어디에서: 공원",
# "누구랑: 스스로/무엇을: 오늘은 혼자 집에서 책을 읽었어. 조용한 공간에서 마음을 가다듬는 것이 좋았어./어디에서: 집",
# "누구랑: 소중한 사람/무엇을: 오늘은 소중한 사람과 함께 카페에서 대화를 나눴어. 함께하는 시간이 소중하고 행복했어./어디에서: 카페",
# "누구랑: 가족/무엇을: 오늘은 가족들과 함께 식사를 했어. 함께하는 것이 기쁘고 행복했어./어디에서: 강남 오제제",
# "누구랑: 친구들/무엇을: 오늘은 친구들과 함께 산책을 다녀왔어. 서로의 이야기를 듣고 걸으면서 마음이 편안해졌어./어디에서: 동네 공원",
# "누구랑: 가족/무엇을: 오늘은 가족들과 함께 집에서 요리를 해먹었어. 함께 만든 음식을 먹으면서 따뜻한 대화를 나누는 것이 기쁘고 행복했어./어디에서: 주방",
# "누구랑: 스스로/무엇을: 오늘은 혼자 집에서 피아노를 치며 시간을 보냈어. 음악에 몰입하면서 마음이 편안해졌어./어디에서: 거실",
# "누구랑: 소중한 사람/무엇을: 오늘은 소중한 사람과 함께 자전거를 타고 여행을 다녀왔어. 함께하는 시간이 특별하고 행복했어./어디에서: 자전거 도로",
# "누구랑: 가족/무엇을: 오늘은 가족들과 함께 영화를 보았어. 함께 보는 것이 기분이 좋았고 특별했어./어디에서: 집"
# "누구랑: 친구/무엇을: 오늘은 친구와 함께 공원에서 테니스를 즐겼어. 함께 승부하고 웃으면서 즐거운 시간을 보냈어./어디에서: 공원 테니스장",
# "누구랑: 동료/무엇을: 오늘은 동료들과 함께 업무 회의를 했어. 함께 아이디어를 나누고 해결책을 찾아가는 과정이 흥미로웠어./어디에서: 회의실",
# "누구랑: 스스로/무엇을: 오늘은 혼자 서점에서 책을 골라 구매했어. 책을 펼치며 시간을 보내는 것이 즐거웠어./어디에서: 서점",
# "누구랑: 자연/무엇을: 오늘은 산으로 등산을 다녀왔어. 힘들었지만 정상에서 바라보는 풍경이 너무 아름다웠어./어디에서: 산",
# "누구랑: 가족/무엇을: 오늘은 가족들과 함께 산책을 다녀왔어. 함께하는 것이 평화로웠어./어디에서: 공원",
# "누구랑: 친구/무엇을: 오늘은 친구와 함께 자전거를 타고 놀았어. 바람을 맞으며 신선한 공기를 마시는 것이 좋았어./어디에서: 자전거도로",
# "누구랑: 동료/무엇을: 오늘은 동료들과 함께 업무 회의를 진행했어. 새로운 아이디어를 공유하는 것이 흥미로웠어./어디에서: 회사",
# "누구랑: 스스로/무엇을: 오늘은 혼자 커피를 마시러 카페에 갔어. 조용한 분위기에서 책을 읽는 것이 기분 좋았어./어디에서: 카페",
# "누구랑: 소중한 사람/무엇을: 오늘은 소중한 사람과 함께 공연을 관람했어. 함께한 시간이 특별하고 기억에 남는 순간이었어./어디에서: 공연장",
# "누구랑: 가족/무엇을: 오늘은 가족들과 함께 집에서 요리를 했어. 함께하는 것이 특별하고 소중했어./어디에서: 집",
# "누구랑: 친구/무엇을: 오늘은 친구와 함께 공원에서 테니스를 즐겼어. 함께 스포츠를 즐기는 것이 기분 좋았어./어디에서: 공원",
# "누구랑: 스스로/무엇을: 오늘은 혼자 영화를 보며 휴식을 취했어. 마음을 가라앉히는 것이 필요했어./어디에서: 집",
# "누구랑: 반려동물/무엇을: 오늘은 반려동물과 함께 공원을 산책했어. 함께하는 것이 행복하고 신선했어./어디에서: 공원",
# "누구랑: 가족/무엇을: 오늘은 가족들과 함께 야외 바베큐를 즐겼어. 함께 음식을 만들고 먹는 것이 즐거웠어./어디에서: 바베큐장",
# "누구랑: 동기 친구들/무엇을: 오늘은 동기 친구들과 함께 프로젝트 회의를 했어. 아이디어를 나누고 계획을 세우는 과정에서 새로운 발견이 많아 좋았어./어디에서: 대학 도서관",
# "누구랑: 연구실 동료/무엇을: 오늘은 연구실 동료들과 함께 실험을 진행했어. 데이터를 분석하고 결과를 공유하면서 함께 성장하는 기분이 들었어./어디에서: 대학 연구실",
# "누구랑: 기숙사 친구들/무엇을: 오늘은 기숙사 친구들과 함께 저녁을 먹었어. 바쁜 일상 속에서도 함께하는 식사는 힐링이 되었어./어디에서: 대학 기숙사 식당",
# "누구랑: 학과 동기/무엇을: 오늘은 학과 동기들과 함께 수업을 들었어. 수업 내용을 공유하고 서로 도움을 주고받으면서 공부하는 것이 효율적이었어./어디에서: 대학 강의실",
# "누구랑: 새로운 친구/무엇을: 오늘은 새로운 친구를 만났어. 함께 커피를 마시면서 이야기를 나누고 서로에 대해 알아가는 시간이 즐거웠어./어디에서: 대학 근처 카페",
# "누구랑: 동아리 동료/무엇을: 오늘은 동아리 동료들과 함께 공연 준비를 했어. 연습하고 소품을 만들면서 팀원들과의 협업이 원활했어./어디에서: 대학 학생회실",
# "누구랑: 스터디 그룹/무엇을: 오늘은 스터디 그룹과 함께 과제를 준비했어. 서로 질문하고 토론하면서 공부하는 과정이 도움이 많이 되었어./어디에서: 대학 도서관",
# "누구랑: 연구실 동료/무엇을: 오늘은 연구실 동료들과 함께 실험 결과를 분석했어. 함께 문제를 해결하고 새로운 아이디어를 고민하는 시간이 유익했어./어디에서: 대학 연구실",
# "누구랑: 동기 친구들/무엇을: 오늘은 동기 친구들과 함께 휴식을 즐겼어. 바쁜 일상에서 벗어나 함께 노는 것이 기분 전환에 좋았어./어디에서: 대학 캠퍼스"

# # Create a cute and funny 8k webtoon style illustration : 
# "A family enjoying a picnic at a park near their home. They are sitting under the shade of a tree, reading books and enjoying snacks prepared by their mother.",
# "With a friend, today I went to see a movie. We enjoyed an exciting action movie and lost track of time. In the end, we finished the day by eating delicious food together. Place: Movie theater.",
# "The picture shows someone resting alone at home today. They are sitting at a desk, lying back on a cushion in front of a computer, and finding peace of mind.",
# "Today, I took a walk in the park with my dog. It felt good to walk under the sunshine and feel the wind on my face. My heart warmed by the lovely sight of my dog.",
# "The picture shows colleagues having a meeting at the office. They are sharing ideas and engaging in discussions, gaining new perspectives and enjoying the sense of collaboration.",
# "A man and his boyfriend went hiking in the mountains today. It was tough, but they cleansed their minds while enjoying the view and listening to the sound of the wind at the summit.",
# "The picture depicts a special celebration at a restaurant. A person is commemorating an anniversary with a loved one, enjoying a delicious dinner together and sharing precious memories.",
# "The picture shows a person spending time alone at home. They are listening to calming music and reflecting on themselves, making self-improvement goals. It is a peaceful moment of self-care and introspection.",
# "A mother and child are cooking together in the kitchen. They are smiling and enjoying the process of making a meal together. The kitchen is filled with warmth and happiness as they prepare and eventually eat the food they made.",
# "The picture shows a group of friends sitting together at a cafe. They are enjoying coffee, having conversations, and spending a good time together.",
# "A child playing happily in the park, creating unforgettable memories with his pure smile while running around.",
# "A couple went on a picnic together today at the park. The time spent with their loved one, accompanied by the sound of rustling tree branches in the wind, was special and joyful.",
# "The picture shows a family watching a movie together at home. They are gathered on a cozy couch, with smiles on their faces, enjoying a warm and comfortable moment together.",
# "In the picture, friends are having a great time riding bicycles in the park, enjoying the breeze and having a fun time together.",
# "The picture is of a person reading a book alone at home. They are enjoying the peace and quiet of their house while relaxing and clearing their mind.",
# "The picture shows a special moment shared with a loved one at a cafe, where two individuals are seen engaged in conversation. The time spent together is cherished and brought happiness to both individuals.",
# "The picture shows a family enjoying a meal together at a restaurant in Gangnam, Ohjehje. They look happy and content, cherishing the time spent together.",
# "A group of friends enjoying a leisurely walk in the neighborhood park, chatting and sharing stories as they stroll, their spirits lifted and relaxed by the peaceful surroundings.",
# "The picture you described shows a family cooking and sharing a meal together at home in the kitchen. They look happy and content while enjoying the food they have prepared together and having warm conversations.",
# "The picture shows a person playing the piano alone at home in the living room. They are fully immersed in the music, finding peace and relaxation in the melody they are creating.",
# "In the picture, a person is riding a bicycle on a dedicated bike lane. They are accompanied by a loved one, making special memories and enjoying a happy time together.",
# "The picture shows a family gathered and enjoying a movie together at home, creating a special and joyful moment.",
# "The picture shows a group of colleagues gathered in a conference room, engaged in a lively discussion during a work meeting. They are sharing ideas and brainstorming together to find solutions, making the process interesting and collaborative.",
# "The picture shows someone alone at a bookstore, happily selecting and buying books. They are seen flipping through a book, enjoying their time spent in the bookstore.",
# "The picture shows a person at the top of a mountain, looking out at a beautiful landscape after finishing a challenging hike.",
# "A family enjoying a peaceful walk together in the park today.",
# "Two friends riding bicycles together on a bike path, enjoying the fresh air and feeling the wind as they have fun biking.",
# "The picture shows coworkers gathered around a table in a meeting room at the office, discussing new ideas and having an engaging work meeting.",
# "The picture shows a person enjoying a quiet moment alone at a cafe. They are reading a book and sipping coffee, savoring the peaceful atmosphere.",
# "The picture shows a special moment at a theater where a person is enjoying a performance with a loved one. The time spent together is precious and memorable.",
# "The picture shows a family cooking together at home. They seem happy and the time spent together is meaningful and special.",
# "The picture shows a friend playing tennis together happily at the park. They are enjoying playing sports together.",
# "The picture shows a person sitting alone comfortably on a sofa at home, watching a movie as a way to relax and unwind. The atmosphere looks calm and peaceful, providing a moment for the individual to soothe their mind.",
# "A person walking in the park with their pet, finding joy and excitement in the companionship and fresh air.",
# "The picture shows a family enjoying an outdoor barbecue together at a barbecue site. They are happily making and eating food together.",
# "A group of classmates sitting around a table in a university library, discussing ideas for a project together. They seem engaged and excited as they share ideas and make plans for their project.",
# "The picture shows a group of colleagues in a university research lab conducting experiments together. They are analyzing data and sharing results, creating a sense of growth and collaboration as they work on their research projects.",
# "In this picture, a group of dormitory friends are gathered around a table in the university dormitory cafeteria, enjoying a meal together. Despite their busy daily lives, sharing a meal together was a healing experience for them.",
# "The picture shows a group of classmates studying together in a university lecture hall. They are sharing notes and helping each other to understand the lesson, making their study session efficient and productive.",
# "The picture shows two people sitting at a cafe near the university, enjoying coffee together. They are engrossed in conversation, getting to know each other and forming a new friendship.",
# "The picture shows a group of club members working together to prepare for a performance in the university student council room. They are practicing and creating props, demonstrating smooth collaboration among team members.",
# "The picture shows a study group working together on their assignments in a university library. They are engaged in asking questions, discussing, and studying together, which has been very helpful for their learning process.",
# "The picture shows a group of university laboratory colleagues analyzing experiment results together. They are seen discussing and brainstorming new ideas to solve problems in the research lab.",
# "The picture shows a group of classmates/friends relaxing and enjoying each other's company on a university campus. They seem to be taking a break from their busy routine and having fun together, helping each other to unwind and destress.",
    diaryToPrompt = {k:v for k,v in zip(diary_lst, prompt_lst)}
    pd.DataFrame(diaryToPrompt)